### PR TITLE
Added project path parameter

### PR DESCRIPTION
**Pull request by zakyvit**
I added method for creating project with path parameter. 
I need it when API automatically replace dot by dash in path.

### CODE REVIEW

**Comment by timols** [comment]
Hey @zakyvit looks like there is duplication in this PR due to your other PR. Would you mind updating this as well?

**Comment by zakyvit** [comment]
I'm sorry I commited to this branch the first PR commits too. But there is one more commit.
You can merge it too.

**Comment by timols** [comment]
@caguilar187 this PR is likely to conflict with yours. Can you verify?

**Comment by caguilar187** [comment]
@timols yes it would. This is also why I created the CreateProjectQuery since maintaining these methods is just messy. I didn't do it in my pull request but I'm of the opinion of marking them deprecated so people switch over in the future. 

@zakyvit my pull request adds this functionality, you will be able to use it in a cleaner way assuming you set null on most of the parameters other than path and name.  Example below.

`api.createProject(new CreateProjectQuery(name).setPath(path));`

**Comment by zakyvit** [comment]
Yes, you are right.

**Pull request closed without merging**
