### PR TITLE
Fixed: GITHUB-297: The "connectTimeout" parameter is not configurable

### PR DESCRIPTION
**Pull request by shaburov**
Refactoring: add getter for host field GitlabAPI &&
remove unused IOException from the method signature

### CODE REVIEW

**Comment by shaburov** [comment]
@timols ^

**Comment by timols** [comment]
@shaburov this is great. Any way to add a test for this?

**Comment by shaburov** [comment]
@timols
I wanted to write tests, but I did not think of how to simulate a case with the error "connection timeout".
With the development of tests for the error "request timeout", problems would not exactly arise. But with this I do not know what to do.

**Comment by timols** [comment]
Unit tests would be a great start!

**Comment by shaburov** [comment]
@timols ^ review please

**Comment by timols** [comment]
@shaburov this is great. Thanks for this contribution!

**Comment by shaburov** [comment]
@timols I am glad to help

**Pull request merged**
