### PR TITLE
Support for GitLab API 4 - Use docker for testing

### PR DESCRIPTION
**Pull request by mfriedenhagen**
This is a followup based on #206 (Java-API changes are all from this PR) for implementing #201.

Tests are already running successfully using gitlab-ce in Docker on Travis. As I am much more familiar with Maven than Gradle and because releases seem to be done with Maven anyway, I switched the build constructions in Travis to use Maven as well.

### CODE REVIEW

**Comment by mfriedenhagen** [comment]
See e.g. https://travis-ci.org/mfriedenhagen/java-gitlab-api/builds/225096735

**Comment by timols** [comment]
@mfriedenhagen this is fantastic. Great work.

How do you feel about adding the travisci widget for the README? I'll get travisci added for this repo as well.

Do you think this is ready to merge?

**Comment by avarne** [comment]
When we can expect the new java-Gitlab_api version which is supported Gitlab API V4

**Comment by mfriedenhagen** [comment]
@timols, I just tried to check all changes as outlined in https://gitlab.com/help/api/v3_to_v4.md, but there are loads. 
* Most of the hard work was already done by @iwarapter. 
* With the docker integration adding additional integration tests should be easier.
* I think we should merge&release this now and then react quickly to upcoming issues (API 3 support will be gone in June AFAIK)

**Pull request merged**
