### PR TITLE
#201 initial support for v3 -> v4 api changes.

### PR DESCRIPTION
**Pull request by iwarapter**
@timols this isnt quite ready yet, however im just putting a docker/travis test harness for this together to get some good functional tests.

### CODE REVIEW

**Comment by mfriedenhagen** [comment]
Probably the major version of java-gitlab-api should be increased because this is not backwards compatible. For easier consumption I would suggest to bump the major to 4 to correspond to the gitlab API version.

**Comment by mfriedenhagen** [comment]
Based on this branch in #207 I provided at least execution of existing tests in travis

**Comment by timols** [comment]
@mfriedenhagen In terms of order, should I merge this PR before #207?

**Comment by mfriedenhagen** [comment]
Hello, PR #207 contains the commit from this one, I am not sure whether I would need to rebase afterwards. Anyway, let's just try:-)

**Comment by timols** [comment]
Going to close this PR since I've merged #207. Thank you very much @iwarapter for this work.

**Pull request closed without merging**
