### PR TITLE
minor cosmetic cleanups

### PR DESCRIPTION
**Pull request by gsmet**
The main changes is the use of the Query API instead of building the query string manually.

### CODE REVIEW

**Comment by timols** [comment]
@gsmet would you mind resolving conflicts so I can merge?

**Comment by gsmet** [comment]
Yes, that's on my todo list. Will do it tonight.

**Comment by timols** [comment]
Great, thanks @gsmet!

**Comment by gsmet** [comment]
Done. You should be able to merge now.

Btw, still interested by a release on Central :).

**Comment by timols** [comment]
1.1.8 is on Central (http://search.maven.org/#artifactdetails%7Corg.gitlab%7Cjava-gitlab-api%7C1.1.8%7Cjar)

Do you mean a release with these changes?

**Comment by gsmet** [comment]
Yes, a release with all the changes of this summer!

**Comment by timols** [comment]
Ok, v1.1.9 has been released, will take a moment to become available!

**Comment by gsmet** [comment]
Nice, thanks!

**Pull request merged**
