### PR TITLE
Check to see if a group has ldap_access as null

### PR DESCRIPTION
**Pull request by MadhavGitlab**

### CODE REVIEW

**Comment by timols** [comment]
@MadhavGitlab I typically avoid having any kind of logic in POJOs. Is there a particular reason the non-null check has to be in the setter?

**Comment by MadhavGitlab** [comment]
@timols I agree with you. Let me see if there is an alternate way to achieve this.

**Comment by MadhavGitlab** [comment]
@timols i added createMergeRequest method

**Comment by MadhavGitlab** [comment]
@timols can you accept this pull request. I will submit a new change for the actual issue of ldap_access. This change has submitting a new merge request.

**Pull request merged**
