### PR TITLE
use Date to parse due_date for GitlabIssue like GitlabMilestone

### PR DESCRIPTION
**Pull request by pikuzi**
This PR was proposed to fix the issue of due_date parse issue.

https://github.com/timols/java-gitlab-api/issues/350

### CODE REVIEW

**Comment by pikuzi** [comment]
close this PR until got the tests fixed.

**Comment by pikuzi** [comment]
complete the commit.
Proposed solution: use Date to parse due_date in GitlabIssue like GitlabMilestone.

**Comment by cowtowncoder** [comment]
Something went wrong here, wrt #351.

**Comment by timols** [comment]
@pikuzi I had to revert this change due to test failures and @cowtowncoder's point regarding breaking API changes

**Pull request merged**
